# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "b066999f152ca49e773e5aa9c2a429326c575149"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.NEMO]]
deps = ["Dates", "Libdl", "OrderedCollections", "Printf", "Scratch", "UUIDs"]
path = "."
uuid = "4b396d75-d59e-4f00-a28a-9025e487bc6f"
version = "0.1.0-DEV"

    [deps.NEMO.extensions]
    NemoMPIExt = ["MPI"]
    NemoMeshArraysExt = ["MeshArrays"]
    NemoNCDatasetsExt = ["NCDatasets"]

    [deps.NEMO.weakdeps]
    MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
    MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
    NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed3d1bb71"

[[deps.OrderedCollections]]
git-tree-sha1 = "05868e21324cede2207c6f0f466b4bfef6d5e7ee"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.8.1"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "9b81b8393e50b7d4e6d0a9f14e192294d3b7c109"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.3.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
